package modelo;

import rmimvc.src.observer.ObservableRemoto;

import java.io.Serializable;

public enum Eventos implements Serializable {
    NOTIFICACION_DESARROLLO_TURNO,
    NOTIFICACION_NUEVO_JUGADOR,
    NOTIFICACION_NUEVA_PARTIDA,
    NOTIFICACION_NUEVA_PARTIDA_PROPIO,
    NOTIFICACION_GANADOR,
    NOTIFICACION_ROBO_CASTIGO,
    NOTIFICACION_HUBO_ROBO_CASTIGO,
    NOTIFICACION_PUNTOS,
    NOTIFICACION_ROBO,
    NOTIFICACION_COMIENZO_PARTIDA,
    NOTIFICACION_COMIENZO_RONDA,
    NOTIFICACION_CORTE_RONDA,
    NOTIFICACION_AGREGAR_OBSERVADOR,
    NOTIFICACION_NUEVA_VENTANA,
    NOTIFICACION_COMIENZO_TURNO,
    NOTIFICACION_FIN_TURNO,
    NOTIFICACION_FIN_PARTIDA,
    JUEGO_INVALIDO,
    YA_NO_PUEDE_BAJAR,
    CANT_MIN_JUGADORES,
    CANT_MAX_JUGADORES,
    FALTAN_JUGADORES,
    INICIAR_PARTIDA,
    PARTIDA_AUN_NO_CREADA,
    NUEVO_MENSAJE
}
